import Footer from "@/components/shared/footer";
import Header from "@/components/shared/header";
import Menu from "@/components/ui/menu";
import type { Metadata } from "next";
import { Manrope } from "next/font/google";
import "./globals.css";

const manrope = Manrope({
  variable: "--font-manrope",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${manrope.className} grid min-h-screen grid-rows-[auto_1fr_auto] antialiased`}
      >
        <Header />
        {children}
        <Footer />
        <Menu />
      </body>
    </html>
  );
}
